version: '3.8'

services:
  renits-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # Optional: Add database service if needed later
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: renits
  #     POSTGRES_USER: renits_user
  #     POSTGRES_PASSWORD: renits_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: