"""Add PatchData table

Revision ID: 5cb00379ab69
Revises: 65166d6629a5
Create Date: 2025-07-31 12:18:11.603505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb00379ab69'
down_revision = '65166d6629a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch_data_model',
    sa.Column('patch_id', sa.String(length=80), nullable=False),
    sa.Column('sugar', sa.Integer(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patch_data_model')
    # ### end Alembic commands ###
